spring.application.name=HireConnect

#PostgreSQL Initialization and dataUpdate everytime
spring.datasource.url=jdbc:postgresql://localhost:5432/hireconnect
spring.datasource.username=postgres
spring.datasource.password=7788
spring.jpa.hibernate.ddl-auto=update